import Head from "next/head";
import Link from "next/link";
import { signOut, useSession } from "next-auth/client";
import styles from "../styles/Layout.module.css";
import { useRouter } from "next/dist/client/router";

const Layout = ({ children }: any) => {
    const [session, loading] = useSession();
    const router = useRouter();

    return (
        <div className={styles.container}>
            <Head>
                <title>Animator Notebook</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.nav}>
                <Link href="/">
                    <a>
                        <h1>Animator Notebook</h1>
                    </a>
                </Link>
                {!session && (
                    <div className={styles.login}>
                        <p>Please sign in to create a notebook.</p>
                        <Link href="/api/auth/signin">
                            <a>
                                <button>Log In</button>
                            </a>
                        </Link>
                    </div>
                )}
                {session && (
                    <button
                        onClick={() => {
                            signOut();
                            router.push("/");
                        }}
                    >
                        <a>Log Out</a>
                    </button>
                )}
            </div>
            {children}
        </div>
    );
};

export default Layout;
