import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { signOut, useSession } from "next-auth/client";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [session, loading] = useSession();

    return (
        <div>
            <Head>
                <title>Animator Notebook</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Animator Notebook</h1>
                {!session && (
                    <div>
                        <p>Please sign in to create a notebook.</p>
                        <Link href="/api/auth/signin">
                            <a>Log In</a>
                        </Link>
                    </div>
                )}
                {session && (
                    <button onClick={() => signOut()}>
                        <a>Log Out</a>
                    </button>
                )}
            </main>
        </div>
    );
}
